# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from View.images import icon


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(612, 486)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        about.setFont(font)
        about.setAutoFillBackground(False)
        about.setStyleSheet("background-color: rgb(155, 171, 184);")
        self.gridLayout = QtWidgets.QGridLayout(about)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=about)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_17 = QtWidgets.QLabel(parent=about)
        self.label_17.setMinimumSize(QtCore.QSize(180, 180))
        self.label_17.setMaximumSize(QtCore.QSize(180, 180))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(QtCore.QByteArray.
                                                                              fromBase64(QtCore.QByteArray(icon)))))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.close_button = QtWidgets.QPushButton(parent=about)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: rgb(150, 126, 118);\n"
"color: rgb(250, 248, 237);")
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=about)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "О программе"))
        self.label.setText(_translate("about", "Сортировка данных методом слияния и пирамидальным"))
        self.close_button.setText(_translate("about", "Закрыть"))
        self.textEdit.setHtml(_translate("about", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа позволяет:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Получать массив данных (размер, левая и права границы вводятся)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Выбирать вид сортировки и её критерий</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Сортировать</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Сохранять результат в текстовый файл</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Производить сравнение двух сортировок по времени выполнения</p></body></html>"))
