# Form implementation generated from reading ui file 'greeting_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_greetings(object):
    def setupUi(self, greetings):
        greetings.setObjectName("greetings")
        greetings.resize(640, 480)
        greetings.setAutoFillBackground(False)
        greetings.setStyleSheet("background-color: rgb(153, 176, 128);")
        self.label = QtWidgets.QLabel(parent=greetings)
        self.label.setGeometry(QtCore.QRect(130, 80, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(250, 248, 237);")
        self.label.setObjectName("label")
        self.open_file_button = QtWidgets.QPushButton(parent=greetings)
        self.open_file_button.setGeometry(QtCore.QRect(170, 210, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.open_file_button.setFont(font)
        self.open_file_button.setAutoFillBackground(False)
        self.open_file_button.setStyleSheet("color: rgb(250, 248, 237);\n"
"background-color: rgb(249, 181, 114);")
        self.open_file_button.setObjectName("open_file_button")
        self.continue_button = QtWidgets.QPushButton(parent=greetings)
        self.continue_button.setGeometry(QtCore.QRect(170, 300, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        self.continue_button.setFont(font)
        self.continue_button.setAutoFillBackground(False)
        self.continue_button.setStyleSheet("color: rgb(250, 248, 237);\n"
"background-color: rgb(249, 181, 114);")
        self.continue_button.setObjectName("continue_button")
        self.about_button = QtWidgets.QPushButton(parent=greetings)
        self.about_button.setGeometry(QtCore.QRect(250, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.about_button.setFont(font)
        self.about_button.setAutoFillBackground(False)
        self.about_button.setStyleSheet("color: rgb(250, 248, 237);\n"
"background-color: rgb(249, 181, 114);")
        self.about_button.setObjectName("about_button")
        self.program_button = QtWidgets.QPushButton(parent=greetings)
        self.program_button.setGeometry(QtCore.QRect(250, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.program_button.setFont(font)
        self.program_button.setAutoFillBackground(False)
        self.program_button.setStyleSheet("color: rgb(250, 248, 237);\n"
"background-color: rgb(249, 181, 114);")
        self.program_button.setObjectName("program_button")

        self.retranslateUi(greetings)
        QtCore.QMetaObject.connectSlotsByName(greetings)

    def retranslateUi(self, greetings):
        _translate = QtCore.QCoreApplication.translate
        greetings.setWindowTitle(_translate("greetings", "Сортировки"))
        self.label.setText(_translate("greetings", "Добро пожаловать"))
        self.open_file_button.setText(_translate("greetings", "Открыть файл"))
        self.continue_button.setText(_translate("greetings", "Продолжить без файла"))
        self.about_button.setText(_translate("greetings", "Об авторе"))
        self.program_button.setText(_translate("greetings", "О программе"))
